enderpearl:
  zones:
    - name: zone1
      cooldown: 10
      x1: 100
      y1: 64
      z1: 100
      x2: 200
      y2: 80
      z2: 200
    - name: zone2
      cooldown: 20
      x1: 300
      y1: 70
      z1: 300
      x2: 400
      y2: 90
      z2: 400
rtp:
  max: 9000
  min: 1000
commands:
  always-disabled:
    - /pl
  disabled-in-combat:
    - /rtp
    - /ec
    - /enderchest
    - /poubelle
    - /shop
    - /hdv
    - /ah
    - /lmsr
    - /poubelle