package fr.redconflict.vote;

import fr.redconflict.RedConflictCore;
import fr.redconflict.db.Database;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Le compteur de votes et la file des lots à remettre.
 *
 * <p>Stocké dans H2, la base du serveur de jeu — pas dans celle du site. Deux
 * raisons : le compte SQL du pont n'a de droits que sur les tables {@code rc_*}
 * et n'aurait pas pu créer celles-ci, et ces données ne regardent que le jeu.
 *
 * <p><b>La file existe parce qu'on vote depuis un navigateur.</b> Le joueur est
 * le plus souvent hors ligne à ce moment-là : les PB peuvent lui être crédités
 * immédiatement, mais un objet doit attendre sa prochaine connexion. Sans cette
 * file, le lot serait perdu — et le joueur aurait voté pour rien.
 */
public final class VoteStorage {

    private final RedConflictCore plugin;
    private final Database db;

    public VoteStorage(RedConflictCore plugin, Database db) {
        this.plugin = plugin;
        this.db = db;
    }

    public boolean isAvailable() {
        return db != null && db.isAvailable();
    }

    /** Crée les deux tables si elles manquent. H2 appartient au plugin : aucun droit à demander. */
    public void ensureTables() {
        String compteurs =
                "CREATE TABLE IF NOT EXISTS vote_counts ("
              + "  uuid    VARCHAR(36) PRIMARY KEY,"
              + "  name    VARCHAR(32) NOT NULL DEFAULT '',"
              + "  total   INT    NOT NULL DEFAULT 0,"
              + "  last_at BIGINT NOT NULL DEFAULT 0)";

        String enAttente =
                "CREATE TABLE IF NOT EXISTS vote_pending ("
              // AUTO_INCREMENT est du MySQL : H2 tourne ici en MODE=PostgreSQL et
              // le refuse. C'est la forme normalisée qu'emploient les autres
              // tables du plugin (hdv, shop, staff).
              + "  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
              + "  uuid       VARCHAR(36) NOT NULL,"
              + "  name       VARCHAR(32) NOT NULL DEFAULT '',"
              + "  lot_id     VARCHAR(64) NOT NULL,"
              + "  created_at BIGINT NOT NULL)";

        try (Connection c = db.getConnection();
             PreparedStatement a = c.prepareStatement(compteurs);
             PreparedStatement b = c.prepareStatement(enAttente)) {
            a.executeUpdate();
            b.executeUpdate();
        } catch (SQLException e) {
            plugin.getLogger().warning("[Vote] Création des tables impossible : " + e.getMessage());
        }
    }

    /**
     * Incrémente le compteur et renvoie le nouveau total.
     *
     * <p>Le total sert à la garantie « tous les N votes ». Il ne se remet jamais
     * à zéro : c'est un cumul de fidélité, pas une série qu'on perd.
     *
     * @return le nombre total de votes, ou 0 si l'écriture a échoué
     */
    public int enregistrerVote(UUID uuid, String name) {
        String sql = "MERGE INTO vote_counts (uuid, name, total, last_at) KEY(uuid) "
                   + "VALUES (?, ?, COALESCE((SELECT total FROM vote_counts WHERE uuid = ?), 0) + 1, ?)";
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, uuid.toString());
            ps.setString(2, name != null ? name : "");
            ps.setString(3, uuid.toString());
            ps.setLong(4, System.currentTimeMillis());
            ps.executeUpdate();
        } catch (SQLException e) {
            plugin.getLogger().warning("[Vote] Compteur : " + e.getMessage());
            return 0;
        }
        return total(uuid);
    }

    public int total(UUID uuid) {
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement("SELECT total FROM vote_counts WHERE uuid = ?")) {
            ps.setString(1, uuid.toString());
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? rs.getInt(1) : 0;
            }
        } catch (SQLException e) {
            return 0;
        }
    }

    /**
     * Remet le compteur de fidélité d'un joueur à zéro.
     *
     * <p>Sert après une série de {@code rcvote} lancés à la main : chaque appel
     * console compte comme un vote et rapproche du coffre des 25, alors qu'aucun
     * vote réel n'a eu lieu.
     *
     * @return true si une ligne existait
     */
    public boolean reinitialiser(UUID uuid) {
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                     "UPDATE vote_counts SET total = 0 WHERE uuid = ?")) {
            ps.setString(1, uuid.toString());
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            plugin.getLogger().warning("[Vote] Remise à zéro du compteur : " + e.getMessage());
            return false;
        }
    }

    /** Met un lot de côté en attendant que le joueur se connecte. */
    public void mettreEnAttente(UUID uuid, String name, String lotId) {
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                     "INSERT INTO vote_pending (uuid, name, lot_id, created_at) VALUES (?,?,?,?)")) {
            ps.setString(1, uuid.toString());
            ps.setString(2, name != null ? name : "");
            ps.setString(3, lotId);
            ps.setLong(4, System.currentTimeMillis());
            ps.executeUpdate();
        } catch (SQLException e) {
            plugin.getLogger().warning("[Vote] Mise en attente : " + e.getMessage());
        }
    }

    /**
     * Récupère et <b>supprime</b> les lots en attente d'un joueur.
     *
     * <p>La suppression a lieu dans la même transaction que la lecture : si le
     * serveur s'arrête entre les deux, le joueur garde ses lots plutôt que de les
     * perdre. Une remise en double est plus acceptable qu'une perte sèche.
     */
    public List<String> retirerEnAttente(UUID uuid) {
        List<String> lots = new ArrayList<>();
        Connection c = null;
        boolean autoCommit = true;
        try {
            c = db.getConnection();
            autoCommit = c.getAutoCommit();
            c.setAutoCommit(false);

            try (PreparedStatement ps = c.prepareStatement(
                    "SELECT lot_id FROM vote_pending WHERE uuid = ? ORDER BY id")) {
                ps.setString(1, uuid.toString());
                try (ResultSet rs = ps.executeQuery()) {
                    while (rs.next()) lots.add(rs.getString(1));
                }
            }

            if (!lots.isEmpty()) {
                try (PreparedStatement ps = c.prepareStatement(
                        "DELETE FROM vote_pending WHERE uuid = ?")) {
                    ps.setString(1, uuid.toString());
                    ps.executeUpdate();
                }
            }
            c.commit();
        } catch (SQLException e) {
            if (c != null) try { c.rollback(); } catch (SQLException ignored) { }
            plugin.getLogger().warning("[Vote] Lecture des lots en attente : " + e.getMessage());
            return new ArrayList<>();
        } finally {
            if (c != null) {
                try { c.setAutoCommit(autoCommit); } catch (SQLException ignored) { }
                try { c.close(); } catch (SQLException ignored) { }
            }
        }
        return lots;
    }

    /** Combien de lots attendent, tous joueurs confondus. Pour /rcvote info. */
    public int enAttenteTotal() {
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement("SELECT COUNT(*) FROM vote_pending");
             ResultSet rs = ps.executeQuery()) {
            return rs.next() ? rs.getInt(1) : 0;
        } catch (SQLException e) {
            return 0;
        }
    }
}
