rtp:
  max: 9000
  min: 1000
commands:
  # Commandes TOUJOURS désactivées pour les non-op (sans le "/" devant)
  always-disabled:
    - pl
    - plugins
    - version
    - ver
    - bukkit:pl
    - bukkit:plugins
  # Commandes désactivées UNIQUEMENT pendant un combat (sans le "/" devant)
  disabled-in-combat:
    - rtp
    - ec
    - enderchest
    - poubelle
    - shop
    - hdv
    - ah
    - lmsr
    - bottlexp
    - trade