package fr.originsfight.shop;

import fr.originsfight.OriginsFightCore;
import fr.originsfight.db.Database;

import java.io.File;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

public class ShopDatabase {
    private static final Logger LOG = Logger.getLogger("Shop-DB");

    private final OriginsFightCore plugin;
    private final Database db;

    public ShopDatabase(OriginsFightCore plugin, Database db) {
        this.plugin = plugin;
        this.db = db;
    }

    // ── Connexion ────────────────────────────────────────────────────────────

    public boolean connect() {
        try {
            createTables();
            LOG.info("[Shop] Base de données (H2) prête.");
            return true;
        } catch (Exception e) {
            LOG.severe("[Shop] EXCEPTION init DB: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }

    /** No-op : le pool est fermé centralement. */
    public void disconnect() { }

    /** Emprunte une connexion au pool — À UTILISER EN TRY-WITH-RESOURCES. */
    public Connection getConnection() throws SQLException { return db.getConnection(); }

    private void createTables() throws SQLException {
        try (Connection c = db.getConnection();
             Statement s = c.createStatement()) {
            s.execute("CREATE TABLE IF NOT EXISTS shop_categories (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(64) NOT NULL," +
                "icon_item VARCHAR(64) NOT NULL DEFAULT 'minecraft:chest', sort_order INT NOT NULL DEFAULT 0);");

            s.execute("CREATE TABLE IF NOT EXISTS shop_items (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category_id INT NOT NULL," +
                "display_name VARCHAR(128) NOT NULL, minecraft_item VARCHAR(64) NOT NULL, meta INT NOT NULL DEFAULT 0," +
                "base_buy_price BIGINT NOT NULL DEFAULT 100, base_sell_price BIGINT NOT NULL DEFAULT 50," +
                "current_buy_price BIGINT NOT NULL DEFAULT 100, current_sell_price BIGINT NOT NULL DEFAULT 50," +
                "max_stack INT NOT NULL DEFAULT 64, frozen INT NOT NULL DEFAULT 0," +
                "floor_price BIGINT NOT NULL DEFAULT 1, ceil_price BIGINT NOT NULL DEFAULT 1000000," +
                "total_buy_volume BIGINT NOT NULL DEFAULT 0, total_sell_volume BIGINT NOT NULL DEFAULT 0," +
                "FOREIGN KEY (category_id) REFERENCES shop_categories(id));");

            // daily=1 → snapshot journalier (affiché dans le graphique)
            s.execute("CREATE TABLE IF NOT EXISTS shop_price_history (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, item_id INT NOT NULL," +
                "timestamp BIGINT NOT NULL, buy_price BIGINT NOT NULL, sell_price BIGINT NOT NULL," +
                "daily INT NOT NULL DEFAULT 0," +
                "FOREIGN KEY (item_id) REFERENCES shop_items(id));");

            s.execute("CREATE TABLE IF NOT EXISTS shop_transactions (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, player_uuid VARCHAR(36) NOT NULL, player_name VARCHAR(32) NOT NULL," +
                "item_id INT NOT NULL, type VARCHAR(8) NOT NULL, quantity INT NOT NULL," +
                "price_unit BIGINT NOT NULL, timestamp BIGINT NOT NULL," +
                "FOREIGN KEY (item_id) REFERENCES shop_items(id));");

            // Événements boursiers (krach, inflation, aubaine)
            s.execute("CREATE TABLE IF NOT EXISTS shop_events (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type VARCHAR(32) NOT NULL," +
                "start_ts BIGINT NOT NULL, end_ts BIGINT NOT NULL," +
                "multiplier_buy DOUBLE NOT NULL DEFAULT 1.0," +
                "multiplier_sell DOUBLE NOT NULL DEFAULT 1.0," +
                "item_ids VARCHAR(1024) NOT NULL DEFAULT ''," +
                "manual INT NOT NULL DEFAULT 0," +
                "announcement VARCHAR(255) NOT NULL DEFAULT '');");
        }
    }

    // ── Événements ────────────────────────────────────────────────────────────

    public long insertEvent(String type, long startTs, long endTs,
                            double multBuy, double multSell,
                            String itemIdsCsv, boolean manual, String announcement) {
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "INSERT INTO shop_events(type,start_ts,end_ts,multiplier_buy,multiplier_sell," +
                "item_ids,manual,announcement) VALUES(?,?,?,?,?,?,?,?)",
                Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, type); ps.setLong(2, startTs); ps.setLong(3, endTs);
            ps.setDouble(4, multBuy); ps.setDouble(5, multSell);
            ps.setString(6, itemIdsCsv == null ? "" : itemIdsCsv);
            ps.setInt(7, manual ? 1 : 0);
            ps.setString(8, announcement == null ? "" : announcement);
            ps.executeUpdate();
            try (ResultSet k = ps.getGeneratedKeys()) { if (k.next()) return k.getLong(1); }
        } catch (SQLException e) { LOG.severe("[Shop] insertEvent: " + e.getMessage()); }
        return -1L;
    }

    public List<ShopEventRow> getActiveEvents() {
        long now = System.currentTimeMillis() / 1000L;
        List<ShopEventRow> list = new ArrayList<>();
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "SELECT * FROM shop_events WHERE end_ts > ? ORDER BY start_ts ASC")) {
            ps.setLong(1, now);
            try (ResultSet rs = ps.executeQuery()) { while (rs.next()) list.add(readEvent(rs)); }
        } catch (SQLException e) { LOG.severe("[Shop] getActiveEvents: " + e.getMessage()); }
        return list;
    }

    public ShopEventRow getEventById(long id) {
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "SELECT * FROM shop_events WHERE id=?")) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) { if (rs.next()) return readEvent(rs); }
        } catch (SQLException e) { LOG.severe("[Shop] getEventById: " + e.getMessage()); }
        return null;
    }

    public void terminateEvent(long id) {
        long now = System.currentTimeMillis() / 1000L;
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "UPDATE shop_events SET end_ts=? WHERE id=? AND end_ts>?")) {
            ps.setLong(1, now); ps.setLong(2, id); ps.setLong(3, now);
            ps.executeUpdate();
        } catch (SQLException e) { LOG.severe("[Shop] terminateEvent: " + e.getMessage()); }
    }

    public void purgeOldEvents() {
        // Supprime les events terminés depuis > 30 jours
        long cutoff = System.currentTimeMillis() / 1000L - 30L * 86400L;
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "DELETE FROM shop_events WHERE end_ts < ?")) {
            ps.setLong(1, cutoff);
            ps.executeUpdate();
        } catch (SQLException ignored) {}
    }

    /** Avance les timestamps de tous les events actifs de 24h (simulation /shopdebug tick all). */
    public void advanceActiveEventsByOneDay() {
        long now = System.currentTimeMillis() / 1000L;
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "UPDATE shop_events SET start_ts = start_ts - 86400, end_ts = end_ts - 86400 WHERE end_ts > ?")) {
            ps.setLong(1, now);
            ps.executeUpdate();
        } catch (SQLException e) { LOG.severe("[Shop] advanceActiveEventsByOneDay: " + e.getMessage()); }
    }

    private ShopEventRow readEvent(ResultSet rs) throws SQLException {
        ShopEventRow e = new ShopEventRow();
        e.id              = rs.getLong("id");
        e.type            = rs.getString("type");
        e.startTs         = rs.getLong("start_ts");
        e.endTs           = rs.getLong("end_ts");
        e.multiplierBuy   = rs.getDouble("multiplier_buy");
        e.multiplierSell  = rs.getDouble("multiplier_sell");
        e.itemIdsCsv      = rs.getString("item_ids");
        e.manual          = rs.getInt("manual") == 1;
        e.announcement    = rs.getString("announcement");
        return e;
    }

    public static class ShopEventRow {
        public long id;
        public String type;
        public long startTs, endTs;
        public double multiplierBuy, multiplierSell;
        public String itemIdsCsv;
        public boolean manual;
        public String announcement;

        public boolean isGlobal() { return itemIdsCsv == null || itemIdsCsv.isEmpty(); }

        public java.util.Set<Integer> getItemIds() {
            java.util.Set<Integer> set = new java.util.HashSet<>();
            if (itemIdsCsv == null || itemIdsCsv.isEmpty()) return set;
            for (String s : itemIdsCsv.split(",")) {
                try { set.add(Integer.parseInt(s.trim())); } catch (NumberFormatException ignored) {}
            }
            return set;
        }
    }

    // ── Catégories ───────────────────────────────────────────────────────────

    public List<ShopCategory> getCategories() {
        List<ShopCategory> list = new ArrayList<>();
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "SELECT id,name,icon_item FROM shop_categories ORDER BY sort_order,id");
             ResultSet rs = ps.executeQuery()) {
            while (rs.next())
                list.add(new ShopCategory(rs.getInt("id"), rs.getString("name"), rs.getString("icon_item")));
        } catch (SQLException e) { LOG.severe("[Shop] getCategories: " + e.getMessage()); }
        return list;
    }

    public int createCategory(String name, String iconItem, int sortOrder) {
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "INSERT INTO shop_categories(name,icon_item,sort_order) VALUES(?,?,?)",
                Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, name); ps.setString(2, iconItem); ps.setInt(3, sortOrder);
            ps.executeUpdate();
            try (ResultSet k = ps.getGeneratedKeys()) { if (k.next()) return k.getInt(1); }
        } catch (SQLException e) { LOG.severe("[Shop] createCategory: " + e.getMessage()); }
        return -1;
    }

    // ── Items ────────────────────────────────────────────────────────────────

    public List<ShopItem> getItemsByCategory(int categoryId) {
        List<ShopItem> list = new ArrayList<>();
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "SELECT i.*,c.name as category_name FROM shop_items i " +
                "JOIN shop_categories c ON i.category_id=c.id WHERE i.category_id=? ORDER BY i.id")) {
            ps.setInt(1, categoryId);
            try (ResultSet rs = ps.executeQuery()) { while (rs.next()) list.add(readItem(rs)); }
        } catch (SQLException e) { LOG.severe("[Shop] getItemsByCategory: " + e.getMessage()); }
        return list;
    }

    public List<ShopItem> getAllItems() {
        List<ShopItem> list = new ArrayList<>();
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "SELECT i.*,c.name as category_name FROM shop_items i " +
                "JOIN shop_categories c ON i.category_id=c.id ORDER BY i.id");
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) list.add(readItem(rs));
        } catch (SQLException e) { LOG.severe("[Shop] getAllItems: " + e.getMessage()); }
        return list;
    }

    public ShopItem getItemById(int itemId) {
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "SELECT i.*,c.name as category_name FROM shop_items i " +
                "JOIN shop_categories c ON i.category_id=c.id WHERE i.id=?")) {
            ps.setInt(1, itemId);
            try (ResultSet rs = ps.executeQuery()) { if (rs.next()) return readItem(rs); }
        } catch (SQLException e) { LOG.severe("[Shop] getItemById: " + e.getMessage()); }
        return null;
    }

    public int createItem(int categoryId, String displayName, String minecraftItem, int meta,
                          long baseBuy, long baseSell, int maxStack, long floor, long ceil) {
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "INSERT INTO shop_items(category_id,display_name,minecraft_item,meta," +
                "base_buy_price,base_sell_price,current_buy_price,current_sell_price," +
                "max_stack,floor_price,ceil_price) VALUES(?,?,?,?,?,?,?,?,?,?,?)",
                Statement.RETURN_GENERATED_KEYS)) {
            ps.setInt(1, categoryId); ps.setString(2, displayName); ps.setString(3, minecraftItem);
            ps.setInt(4, meta); ps.setLong(5, baseBuy); ps.setLong(6, baseSell);
            ps.setLong(7, baseBuy); ps.setLong(8, baseSell);
            ps.setInt(9, maxStack); ps.setLong(10, floor); ps.setLong(11, ceil);
            ps.executeUpdate();
            try (ResultSet k = ps.getGeneratedKeys()) { if (k.next()) return k.getInt(1); }
        } catch (SQLException e) { LOG.severe("[Shop] createItem: " + e.getMessage()); }
        return -1;
    }

    public boolean hasItems() {
        try (Connection c = db.getConnection();
             Statement st = c.createStatement();
             ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM shop_items")) {
            return rs.next() && rs.getInt(1) > 0;
        } catch (SQLException e) { return false; }
    }

    // ── Volumes (mis à jour à chaque transaction, sans toucher aux prix) ─────

    public void recordBuyVolume(int itemId, int quantity) {
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "UPDATE shop_items SET total_buy_volume=total_buy_volume+? WHERE id=?")) {
            ps.setInt(1, quantity); ps.setInt(2, itemId);
            ps.executeUpdate();
        } catch (SQLException e) { LOG.severe("[Shop] recordBuyVolume: " + e.getMessage()); }
    }

    public void recordSellVolume(int itemId, int quantity) {
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "UPDATE shop_items SET total_sell_volume=total_sell_volume+? WHERE id=?")) {
            ps.setInt(1, quantity); ps.setInt(2, itemId);
            ps.executeUpdate();
        } catch (SQLException e) { LOG.severe("[Shop] recordSellVolume: " + e.getMessage()); }
    }

    // ── Historique des prix ──────────────────────────────────────────────────

    public long computeNextDailyTimestamp() {
        long now = System.currentTimeMillis() / 1000L;
        long lastTs = 0;
        try (Connection c = db.getConnection();
             Statement st = c.createStatement();
             ResultSet rs = st.executeQuery("SELECT MAX(timestamp) FROM shop_price_history WHERE daily=1")) {
            if (rs.next()) lastTs = rs.getLong(1);
        } catch (SQLException ignored) {}
        if (lastTs == 0) return now - 6 * 86400L;
        return Math.min(now, lastTs + 86400L);
    }

    public boolean hasDailySnapshots() {
        try (Connection c = db.getConnection();
             Statement st = c.createStatement();
             ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM shop_price_history WHERE daily=1")) {
            return rs.next() && rs.getInt(1) > 0;
        } catch (SQLException ignored) { return false; }
    }

    public void snapshotDailyPrice(int itemId, long buyPrice, long sellPrice, long timestamp) {
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "INSERT INTO shop_price_history(item_id,timestamp,buy_price,sell_price,daily) VALUES(?,?,?,?,1)")) {
            ps.setInt(1, itemId); ps.setLong(2, timestamp);
            ps.setLong(3, buyPrice); ps.setLong(4, sellPrice);
            ps.executeUpdate();
        } catch (SQLException e) { LOG.severe("[Shop] snapshotDailyPrice: " + e.getMessage()); }
    }

    public List<Long> getBuyPriceHistory(int itemId, int maxDays) {
        List<Long> list = new ArrayList<>();
        long sevenDaysAgo = System.currentTimeMillis() / 1000L - 7 * 86400L;
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "SELECT buy_price FROM shop_price_history " +
                "WHERE item_id=? AND daily=1 AND timestamp>=? " +
                "ORDER BY timestamp ASC LIMIT ?")) {
            ps.setInt(1, itemId); ps.setLong(2, sevenDaysAgo); ps.setInt(3, maxDays);
            try (ResultSet rs = ps.executeQuery()) { while (rs.next()) list.add(rs.getLong(1)); }
        } catch (SQLException e) { LOG.severe("[Shop] getBuyPriceHistory: " + e.getMessage()); }
        return list;
    }

    public List<Long> getSellPriceHistory(int itemId, int maxDays) {
        List<Long> list = new ArrayList<>();
        long sevenDaysAgo = System.currentTimeMillis() / 1000L - 7 * 86400L;
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "SELECT sell_price FROM shop_price_history " +
                "WHERE item_id=? AND daily=1 AND timestamp>=? " +
                "ORDER BY timestamp ASC LIMIT ?")) {
            ps.setInt(1, itemId); ps.setLong(2, sevenDaysAgo); ps.setInt(3, maxDays);
            try (ResultSet rs = ps.executeQuery()) { while (rs.next()) list.add(rs.getLong(1)); }
        } catch (SQLException e) { LOG.severe("[Shop] getSellPriceHistory: " + e.getMessage()); }
        return list;
    }

    public void purgeOldPriceHistory() {
        long sevenDaysAgo = System.currentTimeMillis() / 1000L - 7 * 86400L;
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "DELETE FROM shop_price_history WHERE timestamp<?")) {
            ps.setLong(1, sevenDaysAgo);
            int n = ps.executeUpdate();
            if (n > 0) LOG.info("[Shop] Purgé " + n + " entrées historique > 7j");
        } catch (SQLException e) { LOG.severe("[Shop] purgeOldPriceHistory: " + e.getMessage()); }
    }

    // ── Transactions ─────────────────────────────────────────────────────────

    public void logTransaction(String uuid, String name, int itemId, String type, int qty, long priceUnit) {
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "INSERT INTO shop_transactions(player_uuid,player_name,item_id,type,quantity,price_unit,timestamp)" +
                " VALUES(?,?,?,?,?,?,?)")) {
            ps.setString(1,uuid); ps.setString(2,name); ps.setInt(3,itemId);
            ps.setString(4,type); ps.setInt(5,qty); ps.setLong(6,priceUnit);
            ps.setLong(7, System.currentTimeMillis() / 1000L);
            ps.executeUpdate();
        } catch (SQLException e) { LOG.severe("[Shop] logTransaction: " + e.getMessage()); }
    }

    public void purgeOldTransactions() {
        long sevenDaysAgo = System.currentTimeMillis() / 1000L - 7 * 86400L;
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "DELETE FROM shop_transactions WHERE timestamp<?")) {
            ps.setLong(1, sevenDaysAgo);
            int n = ps.executeUpdate();
            if (n > 0) LOG.info("[Shop] Purgé " + n + " transactions > 7j");
        } catch (SQLException e) { LOG.severe("[Shop] purgeOldTransactions: " + e.getMessage()); }
    }

    // ── Stats de marché ──────────────────────────────────────────────────────

    /**
     * Top N items les plus achetés dans les 24 dernières heures.
     * Agrégation pré-calculée en sous-requête (compatible GROUP BY strict H2/PostgreSQL).
     */
    public List<MarketStatEntry> getTopBoughtLast24h(int limit) {
        return getTopByTypeLast24h("BUY", limit);
    }

    /** Top N items les plus vendus dans les 24 dernières heures. */
    public List<MarketStatEntry> getTopSoldLast24h(int limit) {
        return getTopByTypeLast24h("SELL", limit);
    }

    private List<MarketStatEntry> getTopByTypeLast24h(String type, int limit) {
        List<MarketStatEntry> list = new ArrayList<>();
        long since = System.currentTimeMillis() / 1000L - 86400L;
        String sql =
            "SELECT i.*, c.name AS category_name, agg.qty_24h, agg.avg_price FROM (" +
            "  SELECT item_id, SUM(quantity) AS qty_24h, CAST(AVG(price_unit) AS BIGINT) AS avg_price" +
            "  FROM shop_transactions WHERE type=? AND timestamp>=? GROUP BY item_id" +
            ") agg" +
            " JOIN shop_items i ON agg.item_id=i.id" +
            " JOIN shop_categories c ON i.category_id=c.id" +
            " ORDER BY agg.qty_24h DESC LIMIT ?";
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, type); ps.setLong(2, since); ps.setInt(3, limit);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next())
                    list.add(new MarketStatEntry(readItem(rs), rs.getLong("qty_24h"), rs.getLong("avg_price")));
            }
        } catch (SQLException e) { LOG.severe("[Shop] getTopByTypeLast24h(" + type + "): " + e.getMessage()); }
        return list;
    }

    public long getBuyVolumeLast7Days(int itemId) {
        long since = System.currentTimeMillis() / 1000L - 7 * 86400L;
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "SELECT COALESCE(SUM(quantity),0) FROM shop_transactions WHERE item_id=? AND type='BUY' AND timestamp>=?")) {
            ps.setInt(1, itemId); ps.setLong(2, since);
            try (ResultSet rs = ps.executeQuery()) { if (rs.next()) return rs.getLong(1); }
        } catch (SQLException e) { LOG.severe("[Shop] getBuyVolumeLast7Days: " + e.getMessage()); }
        return 0;
    }

    public long getSellVolumeLast7Days(int itemId) {
        long since = System.currentTimeMillis() / 1000L - 7 * 86400L;
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "SELECT COALESCE(SUM(quantity),0) FROM shop_transactions WHERE item_id=? AND type='SELL' AND timestamp>=?")) {
            ps.setInt(1, itemId); ps.setLong(2, since);
            try (ResultSet rs = ps.executeQuery()) { if (rs.next()) return rs.getLong(1); }
        } catch (SQLException e) { LOG.severe("[Shop] getSellVolumeLast7Days: " + e.getMessage()); }
        return 0;
    }

    // ── Régression journalière ────────────────────────────────────────────────

    /**
     * Applique un micro-mouvement de prix IMMÉDIAT à chaque transaction (modèle Kyle 1985).
     */
    public void applyImmediatePriceImpact(int itemId, int qty, boolean isBuy) {
        ShopItem item = getItemById(itemId);
        if (item == null || item.frozen) return;

        double liquidityFactor = Math.max(0.2, Math.min(1.0, item.maxStack / 64.0));
        double lambda = 0.004 / (1.0 + Math.log1p(item.baseBuyPrice / 100.0));
        double impact = lambda * Math.sqrt(qty) / liquidityFactor;

        long buyDelta  = (long)(item.baseBuyPrice  * impact);
        long sellDelta = (long)(item.baseSellPrice * impact);
        buyDelta  = Math.max(1, buyDelta);
        sellDelta = Math.max(1, sellDelta);

        long newBuy, newSell;
        if (isBuy) {
            newBuy  = item.currentBuyPrice  + buyDelta;
            newSell = item.currentSellPrice + sellDelta;
        } else {
            newBuy  = item.currentBuyPrice  - buyDelta;
            newSell = item.currentSellPrice - sellDelta;
        }

        newBuy  = Math.max(item.floorPrice + 1, Math.min(item.ceilPrice, newBuy));
        newSell = Math.max(item.floorPrice,      Math.min(newBuy - 1,    newSell));

        long minSpread = Math.max(1, item.baseBuyPrice / 100);
        if (newBuy - newSell < minSpread) {
            newSell = newBuy - minSpread;
            if (newSell < item.floorPrice) { newSell = item.floorPrice; newBuy = newSell + minSpread; }
        }

        updatePrices(itemId, newBuy, newSell);
    }

    private void updatePrices(int itemId, long nb, long ns) {
        try (Connection c = db.getConnection();
             PreparedStatement ps = c.prepareStatement(
                "UPDATE shop_items SET current_buy_price=?,current_sell_price=? WHERE id=?")) {
            ps.setLong(1,nb); ps.setLong(2,ns); ps.setInt(3,itemId);
            ps.executeUpdate();
        } catch (SQLException e) { LOG.severe("[Shop] updatePrices: " + e.getMessage()); }
    }

    /**
     * Régression journalière — modèle inspiré de la finance de marché
     * (signal offre/demande 7j + momentum 3j + mean-reversion + spread dynamique).
     */
    public void applyDailyPriceRegression() {
        List<ShopItem> all = getAllItems();
        long sevenDaysAgo  = System.currentTimeMillis() / 1000L - 7  * 86400L;
        long threeDaysAgo  = System.currentTimeMillis() / 1000L - 3  * 86400L;

        try (Connection c = db.getConnection();
             PreparedStatement psVol7 = c.prepareStatement(
                "SELECT " +
                "  COALESCE(SUM(CASE WHEN type='BUY'  THEN quantity END),0) AS bv7," +
                "  COALESCE(SUM(CASE WHEN type='SELL' THEN quantity END),0) AS sv7 " +
                "FROM shop_transactions WHERE item_id=? AND timestamp>=?");
             PreparedStatement psVol3 = c.prepareStatement(
                "SELECT " +
                "  COALESCE(SUM(CASE WHEN type='BUY'  THEN quantity END),0) AS bv3," +
                "  COALESCE(SUM(CASE WHEN type='SELL' THEN quantity END),0) AS sv3 " +
                "FROM shop_transactions WHERE item_id=? AND timestamp>=?");
             PreparedStatement psMom = c.prepareStatement(
                "SELECT buy_price FROM shop_price_history " +
                "WHERE item_id=? AND daily=1 ORDER BY timestamp DESC LIMIT 3");
             PreparedStatement psUpd = c.prepareStatement(
                "UPDATE shop_items SET current_buy_price=?,current_sell_price=? WHERE id=?")) {

            final double MAX_MOVE         = 0.25;
            final double REVERSION_CALM   = 0.12;
            final double REVERSION_ACTIVE = 0.04;
            final double MOMENTUM_BOOST   = 1.15;
            final double MOMENTUM_BRAKE   = 0.85;
            final long   ACTIVITY_FLOOR   = 5L;

            for (ShopItem item : all) {
                if (item.frozen) continue;

                psVol7.setInt(1, item.id); psVol7.setLong(2, sevenDaysAgo);
                long buyVol7 = 0, sellVol7 = 0;
                try (ResultSet rs = psVol7.executeQuery()) {
                    if (rs.next()) { buyVol7 = rs.getLong("bv7"); sellVol7 = rs.getLong("sv7"); }
                }

                psVol3.setInt(1, item.id); psVol3.setLong(2, threeDaysAgo);
                long buyVol3 = 0, sellVol3 = 0;
                try (ResultSet rs = psVol3.executeQuery()) {
                    if (rs.next()) { buyVol3 = rs.getLong("bv3"); sellVol3 = rs.getLong("sv3"); }
                }

                psMom.setInt(1, item.id);
                java.util.List<Long> recentPrices = new java.util.ArrayList<>();
                try (ResultSet rs = psMom.executeQuery()) {
                    while (rs.next()) recentPrices.add(rs.getLong("buy_price"));
                }

                long newBuy, newSell;
                boolean marketActive = (buyVol7 + sellVol7) >= ACTIVITY_FLOOR;

                if (!marketActive) {
                    newBuy  = item.currentBuyPrice  + (long)((item.baseBuyPrice  - item.currentBuyPrice)  * REVERSION_CALM);
                    newSell = item.currentSellPrice + (long)((item.baseSellPrice - item.currentSellPrice) * REVERSION_CALM);
                } else {
                    double norm = Math.sqrt((double)buyVol7 * buyVol7 + (double)sellVol7 * sellVol7);
                    double pressure = (norm < 1.0) ? 0.0 : (buyVol7 - sellVol7) / norm;

                    double elasticity = 0.5 + 0.5 * (1.0 - Math.min(1.0, item.baseBuyPrice / 100_000.0));
                    elasticity *= (1.0 + (1.0 - item.maxStack / 64.0) * 0.5);

                    double move = Math.max(-MAX_MOVE, Math.min(MAX_MOVE, pressure * MAX_MOVE * elasticity));

                    newBuy  = item.currentBuyPrice  + (long)(item.baseBuyPrice  * move);
                    newSell = item.currentSellPrice + (long)(item.baseSellPrice * move);

                    if (recentPrices.size() >= 2) {
                        long p0 = recentPrices.get(0);
                        long p1 = recentPrices.get(recentPrices.size() - 1);
                        boolean risingTrend = p0 > p1;
                        boolean buyPressure = pressure > 0.1;
                        boolean sellPressure = pressure < -0.1;

                        if (risingTrend && buyPressure) {
                            newBuy  = (long)(newBuy  * MOMENTUM_BOOST);
                            newSell = (long)(newSell * MOMENTUM_BOOST);
                        } else if (!risingTrend && sellPressure) {
                            newBuy  = (long)(newBuy  * MOMENTUM_BRAKE);
                            newSell = (long)(newSell * MOMENTUM_BRAKE);
                        } else if (risingTrend && sellPressure) {
                            newBuy  = (long)(newBuy  * MOMENTUM_BRAKE);
                            newSell = (long)(newSell * MOMENTUM_BRAKE);
                        }
                    }

                    double activityRatio = Math.min(1.0, (buyVol7 + sellVol7) / 200.0);
                    double reversionAlpha = REVERSION_CALM - (REVERSION_CALM - REVERSION_ACTIVE) * activityRatio;
                    newBuy  += (long)((item.baseBuyPrice  - newBuy)  * reversionAlpha);
                    newSell += (long)((item.baseSellPrice - newSell) * reversionAlpha);

                    if (buyVol3 + sellVol3 >= ACTIVITY_FLOOR) {
                        double norm3 = Math.sqrt((double)buyVol3 * buyVol3 + (double)sellVol3 * sellVol3);
                        double pressure3 = (buyVol3 - sellVol3) / norm3;
                        if (Math.signum(pressure3) == Math.signum(pressure)) {
                            long shortMoveB = (long)(item.baseBuyPrice  * pressure3 * MAX_MOVE * 0.30);
                            long shortMoveS = (long)(item.baseSellPrice * pressure3 * MAX_MOVE * 0.30);
                            newBuy  += shortMoveB;
                            newSell += shortMoveS;
                        }
                    }
                }

                double spreadMultiplier = 1.0;
                if (recentPrices.size() >= 2) {
                    double sumSq = 0.0;
                    for (int i = 1; i < recentPrices.size(); i++) {
                        double pctChange = (double)(recentPrices.get(i) - recentPrices.get(i-1)) / recentPrices.get(i-1);
                        sumSq += pctChange * pctChange;
                    }
                    double volatility = Math.sqrt(sumSq / (recentPrices.size() - 1));
                    spreadMultiplier = 1.0 + volatility * 10.0;
                    spreadMultiplier = Math.max(1.0, Math.min(3.0, spreadMultiplier));
                }

                long baseSpread = Math.max(1, item.baseBuyPrice - item.baseSellPrice);
                long minSpread  = Math.max(1, (long)(baseSpread * spreadMultiplier));

                newBuy  = Math.max(item.floorPrice + minSpread, Math.min(item.ceilPrice, newBuy));
                newSell = Math.min(newSell, newBuy - minSpread);
                if (newSell < item.floorPrice) { newSell = item.floorPrice; newBuy = Math.max(newBuy, newSell + minSpread); }

                psUpd.setLong(1, newBuy);
                psUpd.setLong(2, newSell);
                psUpd.setInt(3, item.id);
                psUpd.addBatch();
            }
            psUpd.executeBatch();
        } catch (SQLException e) { LOG.severe("[Shop] applyDailyPriceRegression: " + e.getMessage()); }
    }

    // ── Chargement du catalogue depuis YAML ──────────────────────────────────

    public boolean loadItemsFromConfig() {
        try {
            File configFile = new File(plugin.getDataFolder(), "shop/shop_items.yml");
            if (!configFile.exists()) plugin.saveResource("shop/shop_items.yml", false);

            org.bukkit.configuration.file.YamlConfiguration config =
                new org.bukkit.configuration.file.YamlConfiguration();
            try (java.io.InputStreamReader reader = new java.io.InputStreamReader(
                    new java.io.FileInputStream(configFile), java.nio.charset.StandardCharsets.UTF_8)) {
                config.load(reader);
            }

            if (!config.contains("categories")) {
                LOG.severe("[Shop] Aucune section 'categories' dans shop_items.yml !");
                return false;
            }
            org.bukkit.configuration.ConfigurationSection catsSection = config.getConfigurationSection("categories");
            if (catsSection == null) return false;

            int totalItems = 0, totalCats = 0;
            for (String catKey : catsSection.getKeys(false)) {
                org.bukkit.configuration.ConfigurationSection cs = catsSection.getConfigurationSection(catKey);
                if (cs == null) continue;
                String catName = cs.getString("name", catKey);
                String catIcon = cs.getString("icon", "minecraft:chest");
                int catSort    = cs.getInt("sort", 999);
                int catId = createCategory(catName, catIcon, catSort);
                if (catId == -1) continue;
                totalCats++;

                for (String line : cs.getStringList("items")) {
                    String[] p = line.split("\\|");
                    if (p.length != 7) continue;
                    String mcItem = p[1]; int meta = 0;
                    if (mcItem.contains(":")) {
                        String[] mp = mcItem.split(":");
                        mcItem = mp[0];
                        try { meta = Integer.parseInt(mp[1]); } catch (NumberFormatException ignored) {}
                    }
                    try {
                        createItem(catId, p[0], mcItem, meta,
                            Long.parseLong(p[2]), Long.parseLong(p[3]),
                            Integer.parseInt(p[4]), Long.parseLong(p[5]), Long.parseLong(p[6]));
                        totalItems++;
                    } catch (NumberFormatException ignored) {}
                }
            }
            LOG.info("[Shop] Catalogue chargé : " + totalCats + " catégories, " + totalItems + " items.");
            return totalItems > 0;
        } catch (Exception e) {
            LOG.severe("[Shop] Erreur chargement shop_items.yml: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }

    // ── Utilitaires admin ────────────────────────────────────────────────────

    public void dropAllShopData() {
        try (Connection c = db.getConnection();
             Statement s = c.createStatement()) {
            s.executeUpdate("DELETE FROM shop_transactions");
            s.executeUpdate("DELETE FROM shop_price_history");
            s.executeUpdate("DELETE FROM shop_items");
            s.executeUpdate("DELETE FROM shop_categories");
        } catch (SQLException e) { LOG.severe("[Shop] dropAllShopData: " + e.getMessage()); }
    }

    public void resetAllPrices() {
        try (Connection c = db.getConnection();
             Statement s = c.createStatement()) {
            s.executeUpdate("UPDATE shop_items SET current_buy_price=base_buy_price," +
                "current_sell_price=base_sell_price,total_buy_volume=0,total_sell_volume=0");
            s.executeUpdate("DELETE FROM shop_price_history");
        } catch (SQLException e) { LOG.severe("[Shop] resetAllPrices: " + e.getMessage()); }
    }

    public String[] getMarketSummary() {
        int items = 0, frozen = 0;
        long bVol = 0, sVol = 0;
        try (Connection c = db.getConnection();
             Statement s = c.createStatement();
             ResultSet rs = s.executeQuery("SELECT COUNT(*),SUM(total_buy_volume)," +
                "SUM(total_sell_volume),SUM(CASE WHEN frozen=1 THEN 1 ELSE 0 END) FROM shop_items")) {
            if (rs.next()) { items=rs.getInt(1); bVol=rs.getLong(2); sVol=rs.getLong(3); frozen=rs.getInt(4); }
        } catch (SQLException e) { LOG.severe("[Shop] getMarketSummary: " + e.getMessage()); }
        return new String[]{
            "§6=== État du Marché ===",
            "§7Catégories : §f" + getCategories().size(),
            "§7Items : §f" + items + " §8(dont §c" + frozen + " gelés§8)",
            "§7Volume Achats : §6" + bVol,
            "§7Volume Ventes : §a" + sVol
        };
    }

    // ── Helpers internes ─────────────────────────────────────────────────────

    private ShopItem readItem(ResultSet rs) throws SQLException {
        ShopItem item = new ShopItem();
        item.id               = rs.getInt("id");
        item.categoryId       = rs.getInt("category_id");
        item.displayName      = rs.getString("display_name");
        item.minecraftItem    = rs.getString("minecraft_item");
        item.meta             = rs.getInt("meta");
        item.baseBuyPrice     = rs.getLong("base_buy_price");
        item.baseSellPrice    = rs.getLong("base_sell_price");
        item.currentBuyPrice  = rs.getLong("current_buy_price");
        item.currentSellPrice = rs.getLong("current_sell_price");
        item.maxStack         = rs.getInt("max_stack");
        item.frozen           = rs.getInt("frozen") == 1;
        item.floorPrice       = rs.getLong("floor_price");
        item.ceilPrice        = rs.getLong("ceil_price");
        item.totalBuyVolume   = rs.getLong("total_buy_volume");
        item.totalSellVolume  = rs.getLong("total_sell_volume");
        item.categoryName     = rs.getString("category_name");
        return item;
    }

    // ── Modèles ──────────────────────────────────────────────────────────────

    public static class MarketStatEntry {
        public final ShopItem item;
        public final long quantity24h;
        public final long avgPrice;
        public MarketStatEntry(ShopItem item, long q, long a) { this.item=item; quantity24h=q; avgPrice=a; }
    }

    public static class ShopCategory {
        public final int id;
        public final String name, iconItem;
        public ShopCategory(int id, String name, String iconItem) { this.id=id; this.name=name; this.iconItem=iconItem; }
    }

    public static class ShopItem {
        public int    id, categoryId, meta, maxStack;
        public String displayName, minecraftItem, categoryName;
        public long   baseBuyPrice, baseSellPrice, currentBuyPrice, currentSellPrice;
        public long   floorPrice, ceilPrice, totalBuyVolume, totalSellVolume;
        public boolean frozen;
    }
}
